#!/bin/sh
set -e
. /usr/local/lib/mame-live/conf
if [ -z "$ML_LOCALE" ] ; then
  exit
fi

mkdir -p /etc
echo "$ML_LOCALE $ML_CHARSET" > /etc/locale.gen
locale-gen
rm -f /etc/locale.gen /etc/locale.alias /etc/default/locale
