#!/bin/sh
set -e
. /usr/local/lib/mame-live/conf
if [ -n "$ML_LOCALE" ] ; then
  mkdir -p /etc
  echo "$ML_LOCALE${ML_CHARSET:+ $ML_CHARSET}" > /etc/locale.gen
  locale-gen
  rm -f /etc/locale.gen
  if [ -e /usr/lib/locale/locale-archive ]; then
    mv /usr/lib/locale/locale-archive /usr/lib/locale/locale-archive.bak
  fi
fi
apt-get purge --yes locales || true
if [ -e /usr/lib/locale/locale-archive.bak ]; then
  mv /usr/lib/locale/locale-archive.bak /usr/lib/locale/locale-archive
fi
