#!/bin/sh

compact_conf() {
  for f in "$@"; do
    sed -i 's/#.*$//' "$f"
    sed -i '/^\s*$/d' "$f"
    sed -i 's/^\s\+\|\s\+$//g' "$f"
  done
}

join_words() {
  local input="$1"
  local delim="$2"
  local prefix="$3"
  local suffix="$4"
  local result
  for s in $input; do
    if [ -n "$s" ]; then
      result="${result:+$result$delim}$prefix$s$suffix"
    fi
  done
  echo "$result"
}

contains_words() {
  local s="$1"
  shift
  local words="$@"
  words="$(join_words "$words" '\n' | sort | uniq)"
  local pattern="$(join_words "$words" '\|')"
  [ "$(echo "$s" | grep -o '\b\('"$pattern"'\)\b' | sort | uniq)" = "$words" ]
}
