#!/bin/sh
mk_cd "${ML_TEST_DIR#/}"
cp "$ML_CONFIG_COMPONENT_DIR"/in_chroot/* .
for comp in $(ls "$ML_AUTO_CONF_LIB"); do
  if [ -f "$ML_AUTO_CONF_LIB/$comp/test" ]; then
    cp "$ML_AUTO_CONF_LIB/$comp/test" "$comp-test"
  fi
done
