#!/bin/sh

_assert_msg() {
  echo "  - $@"
}

_assert_passed() {
  local assert_name="${1:?missing assert name}"
  _assert_msg "Assert $assert_name passed"
}

_assert_failed() {
  local assert_name="${1:?missing assert name}"
  shift
  _assert_msg "Assert $assert_name failed${@:+: expected $@}"
}

assert() {
  local assert_name="${1:?missing assert name}"
  shift
  if [ "$@" ]; then
    _assert_passed "$assert_name"
  else
    _assert_failed "$assert_name" "$@"
}

assert_not_exist() {
  for path in "${@:?missing path}"; do
    if [ -e "$path" ]; then
      _assert_msg "Assert failed: path \"$path\" exists but should not"
    else
      _assert_msg "Assert passed: path \"$path\" doesn't exist"
    fi
  done
}
