#!/bin/sh

cd_chroot_includes
mk_cd etc

echo "$ML_HOSTNAME" > hostname

cat > hosts << EOF
127.0.0.1       localhost $ML_HOSTNAME
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
EOF
