#!/bin/sh
set -e
. /usr/local/lib/mame-live/conf
. "$ML_LIB_DIR/lib-utils"

rm_when_no_mod() {
  local mod="${1:?missing module}"
  shift
  if ! contains_words "$ML_PAM_MODS" "$mod"; then
    rm -rf "$@"
  fi
}

rm -f /etc/pam.conf
compact_conf /etc/pam.d/*

if [ -n "$ML_PAM_MODS" ]; then
  # remove lines in conf files
  ML_PAM_MODS_PATTERN='\(\bpam_\('"$(join_words "$ML_PAM_MODS" '\|')"'\)\.so\b\)\|^@include\b\|^\w\+\s\+include\b'
  for s in /etc/pam.d/*; do
    if grep "$ML_PAM_MODS_PATTERN" "$s" > "$s.tmp"; then
      mv -f "$s.tmp" "$s"
    else
      rm -f "$s.tmp" "$s"
    fi
  done
  ML_PAM_MODS="$(sed -n 's/.*\bpam_\(\w\+\)\.so\b.*/\1/p' /etc/pam.d/* | sort | uniq)"
  ML_PAM_MODS_PATTERN="$(join_words "${ML_PAM_MODS:?all PAM modules are disabled}" '\|')"

  # remove *.so
  ML_PAM_MODS_PATHS="$(ls -d1 /lib*/security/pam_*.so /lib*/*/security/pam_*.so 2>/dev/null | grep -v '\/pam_\('"$ML_PAM_MODS_PATTERN"'\)\.so$')"
  rm -f $ML_PAM_MODS_PATHS

  # remove conf
  ML_PAM_MODS_PATHS="$(ls -d1 /etc/security/* 2>/dev/null | grep -v '\/\(pam_\)\?\('"$ML_PAM_MODS_PATTERN"'\)\(\.\w\+\)\?$')"
  rm -rf $ML_PAM_MODS_PATHS

  find /etc/security/ -type d -empty -delete

  rm_when_no_mod env /etc/environment /etc/default/locale
  rm_when_no_mod securetty /etc/securetty
  rm_when_no_mod shells /etc/shells
  rm_when_no_mod issue /etc/issue /etc/issue.net
  rm_when_no_mod lastlog /var/log/lastlog
  rm_when_no_mod motd /etc/motd
fi
