#!/bin/sh
set -e

for mod in issue time access limits lastlog motd; do
  sed -i '/^[^#].*pam_'$mod'\.so/s/^/# /' /etc/pam.d/*
done
for s in $(ls -d /etc/pam.d/*); do
  sed -i '/^\s*#/d' "$s"
  sed -i '/^$/d' "$s"
done
