#!/bin/sh
set -e

for mod in issue time access limits lastlog motd; do
  sed -i '/^[^#].*pam_'$mod'\.so/s/^/# /' /etc/pam.d/*
done
for s in $(ls /etc/pam.d/*); do
  sed -i '/^\s*#/d' "/etc/pam.d/$s"
  sed -i '/^$/d' "/etc/pam.d/$s"
done
