#!/bin/sh
set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log

find -P config -name '*.auto-mame-live' -exec rm -f '{}' '+'
find -P config -name '*.auto-mame-live.*' -exec rm -f '{}' '+'
find -P config -type l -exec rm -f '{}' '+'
