#!/bin/sh
set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log

rm -f config/includes.chroot/etc/sudoers.d/mame-live
find -P config -type l -exec rm -f '{}' '+'
