#!/bin/sh
set -e

set -o allexport
. auto/config-init
set +o allexport

# lb config
lb config noauto \
  --iso-volume mame-live \
  --tasksel apt \
  --system live \
  --binary-images iso-hybrid \
  --distribution testing \
  --archive-areas main \
  --architectures amd64 \
  --debian-installer false \
  --security false \
  --updates false \
  --backports false \
  --memtest none \
  --win32-loader false \
  --bootloaders grub-efi \
  --debootstrap-options '--variant=minbase' \
  --bootappend-live "boot=live quiet nosplash noeject ip=frommedia components=tzdata,util-linux,hooks hooks=filesystem ${TZ:+timezone=$TZ}" \
  "${@}"

  #--apt-recommends false \
  #--apt-indices false \
  #--firmware-chroot false \

. auto/config-utils
. auto/config-tasks

# Main
if [ "$MINIMAL" = true ]; then
  minimal_chroot_hooks
else
  extra_tools
fi
live_config_env
hostname
locale
