#!/bin/sh
set -e

if [ -e /etc/timezone ]; then
  TZ="timezone=$(cat /etc/timezone)"
fi
readonly USERNAME=user

lb config noauto \
  --iso-volume mame-live \
  --tasksel apt \
  --system live \
  --binary-images iso-hybrid \
  --distribution testing \
  --archive-areas main \
  --architectures amd64 \
  --debian-installer false \
  --security false \
  --updates false \
  --backports false \
  --memtest none \
  --win32-loader false \
  --bootloaders grub-efi \
  --debootstrap-options '--variant=minbase' \
  --bootappend-live "boot=live quiet nosplash noeject components=hostname,user-setup,locales,tzdata,util-linux,login username=$USERNAME $TZ" \
  "${@}"

  #--apt-recommends false \
  #--apt-indices false \
  #--firmware-chroot false \
  #todo: components

if [ -n "$DEV" ]; then
  ln -rs auto/dev-tools.list.chroot config/package-lists/dev-tools.auto-mame-live.list.chroot
  mkdir -p config/includes.chroot/etc/sudoers.d/
  echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" > config/includes.chroot/etc/sudoers.d/nopwd.auto-mame-live
  chmod 0440 config/includes.chroot/etc/sudoers.d/nopwd.auto-mame-live
else
  ln -rs auto/apt-minimal.hook.chroot config/hooks/normal/9975-apt-minimal.auto-mame-live.hook.chroot
  ln -rs auto/dpkg-minimal.hook.chroot config/hooks/normal/9985-dpkg-minimal.auto-mame-live.hook.chroot
fi
