#!/bin/sh
set -e
readonly ML_LIB="$(dirname "$(readlink -m "$0")")"
readonly ML_BASE_DIR="$(dirname "$ML_LIB")"
readonly ML_CONFIG_COMPONENT="${1:?missing component}"
readonly ML_CONFIG_COMPONENT_DIR="$ML_LIB/$ML_CONFIG_COMPONENT"
. "$ML_LIB/utils"

component_run() {
  cd "$ML_CONFIG_COMPONENT_DIR"
  . "$ML_CONFIG_COMPONENT_DIR/${1:?missing script}"
  cd "$ML_CONFIG_COMPONENT_DIR"
}

run_chroot_includes() {
  component_run chroot-includes
}

echo "Config $ML_CONFIG_COMPONENT"
. "$ML_CONFIG_COMPONENT_DIR/config"
