#!/bin/sh
readonly ML_PACKAGE_LISTS="$ML_BASE_DIR/config/package-lists"
readonly ML_CHROOT_INCLUDES="$PWD/config/includes.chroot"
readonly ML_CHROOT_HOOKS="$PWD/config/hooks/normal"

cd_chroot_includes() {
  cd "$ML_CHROOT_INCLUDES"
}

mk_cd() {
  local path="${1:?missing path}"
  mkdir -p "$path"
  cd "$path"
}

ln_chroot_hook() {
  local priority="${1:-8000}"
  local path="${2:-chroot-hook}"
  local name="${3:-$ML_CONFIG_COMPONENT}"
  ln -sf "$ML_CONFIG_COMPONENT_DIR/${path#/}" "$ML_CHROOT_HOOKS/$priority${name:+-$name}.mame-live.hook.chroot"
}
