#!/bin/sh
readonly _CHROOT_INCLUDES="$PWD/config/includes.chroot"
readonly _CHROOT_HOOKS="$PWD/config/hooks/normal"

cd_chroot_includes() {
  pushd .
  cd "$_CHROOT_INCLUDES"
}

ln_chroot_hook() {
  local path="${1:-chroot-hook}"
  local name="${2:-$ML_CONFIG_COMPONENT}"
  local priority="${3:-8000}"
  ln -rs "$path" "$_CHROOT_HOOKS/$priority${name:+-$name}.mame-live.hook.chroot"
}
