#!/bin/sh

_assert_msg() {
  echo "  - $@"
}

_assert_pass() {
  local assert_name="${1:?missing assert name}"
  _assert_msg "PASS $assert_name"
}

_assert_fail() {
  local assert_name="${1:?missing assert name}"
  shift
  _assert_msg "FAIL $assert_name: $@"
}

assert() {
  local assert_name="${1:?missing assert name}"
  shift
  if "$@"; then
    _assert_pass "$assert_name"
  else
    _assert_fail "$assert_name" "$@"
  fi
}

assert_not_exist() {
  for path in "${@:?missing path}"; do
    if [ -e "$path" ]; then
      _assert_msg "FAIL: path \"$path\" exists but should not"
    else
      _assert_msg "PASS: path \"$path\" doesn't exist"
    fi
  done
}

assert_no_packages() {
  for package in "${@:?missing package}"; do
    if [ -e "/var/lib/dpkg/info/$package.list" ]; then
      _assert_msg "FAIL: package \"$package\" exists but should not"
    else
      _assert_msg "PASS: package \"$package\" doesn't exist"
    fi
  done
}
