#!/bin/sh

_assert_msg() {
  echo "  - $@"
}

_assert_pass() {
  _assert_msg "PASS$@"
}

_assert_fail() {
  _assert_msg "FAIL$@"
  ML_TEST_FAIL=true
}

assert() {
  local assert_name="${1:?missing assert name}"
  shift
  if "$@"; then
    _assert_pass " $assert_name"
  else
    _assert_fail " $assert_name: $@"
  fi
}

assert_not_exist() {
  for path in "${@:?missing path}"; do
    if [ -e "$path" ]; then
      _assert_fail ": path \"$path\" exists but should not"
    else
      _assert_pass ": path \"$path\" doesn't exist"
    fi
  done
}

assert_no_packages() {
  for package in "${@:?missing package}"; do
    if [ -e "/var/lib/dpkg/info/$package.list" ]; then
      _assert_fail ": package \"$package\" is installed but should not"
    else
      _assert_pass ": package \"$package\" is not installed"
    fi
  done
}

assert_compact_conf() {
  if grep -q '#\|^\s*$\|^\s\+\|\s\+$' "$@"; then
    _assert_fail " not compact: $@"
  else
    _assert_pass " compact: $@"
  fi
}
