#!/bin/sh
. /usr/local/lib/mame-live/conf
. "$ML_LIB_DIR/lib-utils"
cd "$ML_LIB_DIR/test"
. ./asserts

run_test() {
  local test_name="${1:?missing test name}"
  test_name="${test_name%-test}"
  echo "Test $test_name"
  ML_TEST_FAIL=false
  . "./${test_name}-test"
  if [ "$?" -ne 0 ] || [ "$ML_TEST_FAIL" = true ]; then
    ML_FAILED_TESTS="${ML_FAILED_TESTS:+$ML_FAILED_TESTS }$test_name"
  fi
}

ML_TESTS="${@:-$(ls -d *-test)}"
ML_TOTAL_TESTS=$(echo "$ML_TESTS" | wc -w)
for test_name in $ML_TESTS; do
  run_test "$test_name"
done
if [ -z "$ML_FAILED_TESTS" ]; then
  echo "\e[92m$ML_TOTAL_TESTS out of $ML_TOTAL_TESTS test(s) passed.\e[39m"
else
  echo "\e[91m$(echo "$ML_FAILED_TESTS" | wc -w) out of $ML_TOTAL_TESTS test(s) failed: $ML_FAILED_TESTS\e[39m"
fi
