#!/bin/sh
cd_chroot_includes
mk_cd "$ML_TEST_DIR"

env | sed -n '/^ML_\w\+=/p' > conf
cp "$ML_CONFIG_COMPONENT_DIR"/in_chroot/* .
for comp in $(ls "$ML_LIB"); do
  if [ -f "$ML_LIB/$comp/test" ]; then
    cp "$ML_LIB/$comp/test" "$comp-test"
  fi
done
